### ISSUE TITLE
外层容器css缩放，导致无法正常拖拽节点

### ISSUE THREAD

**Issue by WX-DongXing** [antvis/G6#1175]
* **G6 Version**: 3.2.3
* **Platform**: macbook pro 10.15.2
* **Mini Showcase(like screenshots)**: 
![g6](https://user-images.githubusercontent.com/25719069/73809174-5f5e1f00-480d-11ea-9a0d-83441d6d4e4e.gif)

* **CodePen Link**: https://codepen.io/dongxing/project/editor/XWjMaN

对外层容器进行css  缩放时候，无法正确获取节点的位置，导致无法正确拖拽节点

```css
#container {
    transform: scale(1.2);
}
```
