### ISSUE TITLE
G6中运用了Grid插件 但是网格不显示

### ISSUE THREAD

**Issue by 751971230** [antvis/G6#1897]
- **G6 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by Yanyan-Wang** [comment]
审查一下元素，应该是被盖住了，调整一下 z-index

**Comment by 751971230** [comment]
试了下，如果吧zindex调高，他会遮盖住canves画布无法操作了，也没有别的样式影响呀

**Comment by Yanyan-Wang** [comment]
grid 如果在画布下面一层，并且画布没有背景色，应该不会看不到吧。看不到是不是被除了其他画布以外的元素盖住了。

**Comment by FxPixels** [comment]
minimap，grid，canvas 三者显示层级都需要有所改动才行
@Yanyan-Wang 
less 代码：

` #mountNode {
    .minimap{
      position: absolute;
      top: 40px !important;
      left: 40px !important;
      border-width: 1px;
      border-style: solid;
      z-index: 10;
    }

    canvas {
      position: relative;
    }
    
    .g6-grid-container{
      z-index: 0 !important;
      background-color: #fff;
    }
  }`

**Comment by bitbw** [comment]
我在vuetify中 使用 不好使 因为有默认样式
```scss
 *, ::before, ::after{
   background-repeat: no-repeat;
 }
```

添加样式覆盖
```scss
// 网格位置 
.g6-grid-container {
 z-index: 0 !important;
  *, ::before, ::after{
    // 覆盖 vuetify  background-repeat: no-repeat;
    background-repeat: repeat;
  }
}
```
