### ISSUE TITLE
 G6. There is a styling issue with Minimap

### ISSUE THREAD

**Issue by NidhoggDJoking** [antvis/G6#6350]
### Describe the bug / 问题描述

 G6.Minimap 存在样式问题，图形缩放至最小时 Minimap 的边框出现如图问题，Minimap 中viewport 边框 显示部分有差异

使用 G6.ImageMinimap 正常

![1726645771078](https://github.com/user-attachments/assets/0a70c6ea-126e-42a7-8fe2-c753d69e14b2)

### Reproduction link / 重现链接

https://g6.antv.antgroup.com/examples/tool/minimap/#minimap

### G6 Version / G6 版本

🆕 4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

### Additional context / 补充说明

```css
.g6-minimap-viewport{
    transform: translate(-1px, -1px);
}
```

目前我是加入`transform` 这个才能正常的
